### ISSUE TITLE
tabel rab

### ISSUE THREAD

**Issue by anggarasaja** [datadigicore/siprisdik#3]
- [ ] tambahin tooltip di kode rkakl
- [x] FIKRI - tambahin report pengajuan di status belum diajukan

**Comment by anggarasaja** [comment]
@ghaffargebe @datadigicore ini tooltip buat apa ya kemarin ?

**Comment by ghaffarrizqi** [comment]
@anggarasaja buat penjelasan nama akunnya ris. itu kan masi kode doang. nah tambahin namanya

**Comment by andrecun** [comment]
Gmn progressnya?
Pada tanggal 29 Mar 2016 22.31, "Ghaffar Rizqi" notifications@github.com
menulis:
