### ISSUE TITLE
Tampilan RAB

### ISSUE THREAD

**Issue by ghaffarrizqi** [datadigicore/siprisdik#9]
- [x] tampilan awal pas klik RAB diganti .
  kalo yang sekarang masih per uraian acara. 
  nah sekarang ditambahin sebelum itu munculin tabel yang isinya kode rkakl, jumlah pagu, realisasi, usulan, sisa, dan aksi. ini cuma diambil dari tabel rkakl_full. kaya di gambar
  <img width="905" alt="screen shot 2016-03-30 at 08 53 13" src="https://cloud.githubusercontent.com/assets/11608982/14129518/f517d18a-f654-11e5-8b08-aa2e9568ac73.png">
- [x] terus pas klik view baru muncul kaya yg ada sekarang. tp gausa pake kode rkakl lg. nih kaya di gambar.
  <img width="828" alt="screen shot 2016-03-30 at 08 55 00" src="https://cloud.githubusercontent.com/assets/11608982/14129547/1e96eb54-f655-11e5-9446-d1bfdfd11aae.png">
- [x] untuk tambah RAB nya masih sama. bedanya adalah kode rkakl nya gabisa dipilih lagi. jd readonly aja. karena udah dipilih dr tabel pertama.

kalo ga ngerti bilang ya, gw agak belibet jelasinnya hahaha

**Comment by anggarasaja** [comment]
di kolom output sampe subkomponen ada "nama" itu nama apaan ?

**Comment by ghaffarrizqi** [comment]
maksud gw nama si outputnya. misalnya "001 - Layanan Perkantoran"

**Comment by ghaffarrizqi** [comment]
ris poin 2 sama 3 nya masih ada yg salah kayanya. poin 1 udah bner kok.
